First review with my comments
nolka/telegram-antispam-bot pull request #19
Opened 2023-09-22 09:59 UTC by sibiry-k

2023-09-22 10:16 UTC, nolka requested changes

2023-09-22 10:16 UTC, nolka commented on bot.py
> +'''Тут непосредственно представлена логика работы бота'''
Докстринги нужно писать обернув их в двойные кавычки а не одинарные. Точку забыл поставить в конце

2023-09-22 10:16 UTC, nolka commented on bot.py
> +import telebot  # Линтер ругается, что не может импортировать tetlebot
Запусти в virtualenv команду pip install -r requirements.txt

2023-09-22 10:16 UTC, nolka commented on bot.py
> +# Линтер ругается, что не может импортировать telebot.apihelper
Запусти в virtualenv команду pip install -r requirements.txt

2023-09-22 10:16 UTC, nolka commented on bot.py
> +    """Class used to exid from worker threads."""
Класс нужен для завершения работы потока, отправляющего сообщения в телегу

2023-09-22 10:16 UTC, nolka commented on bot.py
> +                # Перехват слишком общего исключения, я так понимаю,
На это предупреждение можешь забить. Такой прием позволяет не падать приложению в случае если когда вылезло неожиданное исключение.

2023-09-22 10:16 UTC, nolka commented on bot.py
> +    def on_chat_message(self, message):  # Тут просто нужно добавить Docstring
Добавь

2023-09-22 10:16 UTC, nolka commented on main.py
> +# линтер ругается, на то, что не может импортировать телебот, хотя pip list говорит
Запусти в virtualenv команду pip install -r requirements.txt

2023-09-22 10:16 UTC, nolka commented on main.py
> +# линтер ругается, на то, что не может импортировать dotenv, хотя pip list говорит
Запусти в virtualenv команду pip install -r requirements.txt

2023-09-22 10:16 UTC, nolka commented on main.py
> +from bot import Engine  # Тут мы импортируем Engine из bot.py и т.д. ниже по коду
Да, импортируем. Нам же нужно как-то управлять ботом)

2023-09-22 10:16 UTC, nolka commented on main.py
> +# Выше так называемый Docstring, у нас его принято оформлять иначе.
По докстрингам есть спека: https://peps.python.org/pep-0257/#specification

2023-09-22 10:16 UTC, nolka commented on main.py
> +    storage = FileSystem(os.path.join
Чем форматировал?

2023-09-22 10:16 UTC, nolka commented on main.py
> +    def handle_ctrlc(signum, frame):  # Эта функция тормозит бота по нажатию Ctrl+C
Переименуй оба аргумента в _

2023-09-22 10:16 UTC, nolka commented on storage.py
> +        # Здесь и далее линтер ругается на отсутвие Docstring
Добавь

2023-09-22 10:16 UTC, nolka commented on views.py
> +# Не может импортировать jinja2
Запусти в virtualenv команду pip install -r requirements.txt

2023-09-22 10:17 UTC, nolka commented
Конфликты еще нужно разрешить

2023-10-01 09:37 UTC, sibiry-k commented on bot.py
> +import telebot  # Линтер ругается, что не может импортировать tetlebot
_$ pip list
Package            Version
------------------ ---------
certifi            2023.7.22
charset-normalizer 3.2.0
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.3
pip                23.2.1
pyTelegramBotAPI   4.13.0
python-dotenv      1.0.0
requests           2.31.0
setuptools         58.1.0
telebot            0.0.5
urllib3            2.0.5_

2023-10-01 09:38 UTC, sibiry-k commented on bot.py
> +'''Тут непосредственно представлена логика работы бота'''
Это не докстринг, а коммент я пытался. Ну ок, пусть будет докстринг.

2023-10-01 09:38 UTC, sibiry-k commented on bot.py
> +# Линтер ругается, что не может импортировать telebot.apihelper
см.выше

2023-10-01 09:40 UTC, sibiry-k commented on main.py
> +    storage = FileSystem(os.path.join
руками

2023-10-01 09:49 UTC, sibiry-k commented on main.py
> +    def handle_ctrlc(signum, frame):  # Эта функция тормозит бота по нажатию Ctrl+C
+

2023-10-01 10:02 UTC, sibiry-k commented on storage.py
> +        # Здесь и далее линтер ругается на отсутвие Docstring
Збс, чтоб добавлять докстринги нужно понимать о чем функции :))

2023-10-01 10:02 UTC, sibiry-k commented on views.py
> +# Не может импортировать jinja2
$ pip list
Package            Version
------------------ ---------
certifi            2023.7.22
charset-normalizer 3.2.0
idna               3.4
**Jinja2             3.1.2**
MarkupSafe         2.1.3
pip                23.2.1
pyTelegramBotAPI   4.13.0
python-dotenv      1.0.0
requests           2.31.0
setuptools         58.1.0
telebot            0.0.5
urllib3            2.0.5

2023-10-01 12:22 UTC, closed without merging